Support empty token_ids returned from model (#89)
The OLMo 7B model does not currently return `token_ids`, which caused an
error:
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.11/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/api/src/v3.py", line 439, in stream
    part = OutputPart.from_struct(resp.result.output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/src/v3.py", line 60, in from_struct
    return cls(op["text"], [int(tid) for tid in op["token_ids"]], logprobs, fr)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'token_ids'
```

This PR makes them not required, as we are not storing them.